sudo: false
language: objective-c
osx_image: xcode7.2
xcode_workspace: CXDurationPickerDemo/CXDurationPickerDemo.xcworkspace
xcode_scheme: CXDurationPickerDemo
xcode_sdk: iphonesimulator
podfile: CXDurationPickerDemo/Podfile

before_install:
  - gem install slather --no-ri --no-rdoc
